

# print("welcome")
# card=input("insert the card")
# if card=="ATM card":
#     print("transction in process")
#     language=input("select the language")
#     if language=="marathi" or language=="english":
#         print("in process")
#         PIN=int(input("enter the PIN"))
#         if PIN==1721:
#             print("in process")
#             account=input("type of account")
#             if account=="saving a/c" or account=="current a/c":
#                 print("in process")
#                 transction_type=input("enter the type of transction")
#                 if transction_type=="cash withdraw":
#                     print("in process") 
#                     amount=int(input("enter the amount"))
#                     if amount<10000:
#                         print("transction is in process")
#                         print("collect your amount")
#                         receipt=input("do you want receipt")
#                         if receipt=="yes":
#                             print("get receipt")
#                             print("collect your card")
#                             print("thank you")
#                         else:
#                             print("dont get receipt")
#                     else:
#                         print("invalid transction")
#                 else:
#                     print("no cash")
#             else:
#                 print("invalid transction")
#         else:
#             print("invalid transction")
#     else:
#         print("no this language")
# else:
#     print("invalid card")
