# day=input("enter the day")
# meal=input("enter the breakfast,lunch,dinner")
# if day=="monday":
#     if meal=="breakfast":
#         print("poha")
#     elif meal=="lunch":
#         print("rajma chawal")
#     else:
#         print("roti sabzi")
# elif day=="tuesday":
#     if meal=="breakfast":
#         print("poori sabzi")
#     elif meal=="lunch":
#         print("thukpa")
#     else:
#         print("chikan chawal")
# else:
#     print("and any day eat roti sabzi")
