# a=int(input("enter the number"))
# b=int(input("enter the number"))
# c=int(input("enter the number"))
# if(a>b):
#     if(a>c):
#         if(b>c):
#             print("2nd greter is %d",c)
#         else:
#             print("2nd greter is %d",b)
# else:
#     print("invalid")
# if(b>c):
#     if(c>a):
#         print("2nd greter is %d",a)
#     else:
#         print("2nd greter is %d",c) 
# else:
#     print("2nd greter is %d",b)   
