# a=int(input("enter the number"))
# b=int(input("enter the number"))
# c=int(input("enter the number"))
# if c>a>b:
#     print(a,"second greatest")
# elif c<a<b:
#     print(a,"second greatest")
# elif c>b>a:
#     print(b,"second greatest")
# elif c<b<a:
#     print(b,"second greatest")
# elif b>c>a:
#     print(c,"second greatest")
# elif b<c<a:
#     print(c,"second greatest")
# else:
#     print("code end thanks")

