
# num=input("enter the password")
# if len(num)>6 or len(num)<16:
#     if "A" in num or "z" in num:
#         if "2" in num or "8" in num:
#             if "$" in num:
#                 print("it is strong password")
#             else:
#                 print("weak password")
#         else:
#             print("weak password")
#     else:
#         print("weak password")
# else:
#     print("weak password")
