# time=(input("enter the time"))
# if time>="6" and time<"7":
#     print("it is excersise time")
# elif time>="7" and time<"8.30":
#     print("it is 1st break time")
# elif time>="8.30" and time<"9.30":
#     print("it is english activity time")
# elif time>="09.30" and time<"13.00":
#     print("it is coding time")
# elif time>="13" and time<"14.30":
#     print("it is lunch break time")
# elif time>="14.30" and time<"16":
#     print("it is cultural activity time")
# elif time>="16" and time<"16.30":
#     print("it is 2nd break time")
# elif time>="16.30" and time<"21":
#     print("again coding time")
# elif time>"21":
#     print("it is dinner time")
# else:
#     print("ivalid")

