# username=input("enter the username")
# if username=="gauripatil":
#     print("correct username")
#     pass_word=int(input("enter the password"))
#     if pass_word==1234:
#         print("login sucssesful")
#     elif pass_word!=1234: 
#         print("create new account")
#     else:
#         print("invalid")
# elif username!="gauripatil":
#     print("invalid")
#     user_name=input("enter the user_name")
#     new_password=int(input("enter the new_password"))
#     if user_name=="ankitapatil":
#         if new_password==4567:
#             print(user_name,new_password,"create account")
#         else:
#             print("invalid")
#     else:
#         print("invalid")
# else:
#     print("invalid")